aggregation_stereotype:
  name: subCollectionOf
  directed: true
  source_end:
    allowed: Collective
    min: 1
    max: *
    readOnly: undefined
  target_end:
    allowed: Collective
    min: 1
    max: 1
    readOnly: undefined
  binary_properties:
    reflexivity: false
    transitivity: false
    symmetry: false
    cyclicity: false
